version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "golambdademo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-o3n0t5rf6nfc"
s3_prefix = "golambdademo"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
