AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda comparison

Parameters:
  ThundraAWSAccountNo:
    Type: Number
    Default: 269863060030

  ThundraNodeLayerVersion:
    Type: Number
    Default: 105
  ThundraPythonLayerVersion:
    Type: Number
    Default: 56
  ThundraJavaLayerVersion:
    Type: Number
    Default: 65

Globals:
  Function:
    Timeout: 20
    Environment:
      Variables:
        thundra_apiKey: <Thundra Api key>
    MemorySize: 512

Resources:
  DotNet31Function:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: DotnetCore31-HelloWorld
      CodeUri: ./dotnetcore3.1/src/HelloWorld/
      Handler: Thundra.Agent::Thundra.Agent.Lambda.Core.ThundraProxy::Handle
      Runtime: dotnetcore3.1
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          thundra_agent_lambda_handler: HelloWorld::HelloWorld.Function::FunctionHandler
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /dotnet31
            Method: get
  Java11Function:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: Java11-HelloWorld
      CodeUri: java11/HelloWorldFunction
      Handler: io.thundra.agent.lambda.core.handler.ThundraLambdaHandler
      Runtime: java11

      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          THUNDRA_AGENT_LAMBDA_HANDLER: helloworld.App::handleRequest
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /java11
            Method: get
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:${ThundraAWSAccountNo}:layer:thundra-lambda-java-layer:${ThundraJavaLayerVersion}

  Go10Function:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: Go1x-HelloWorld
      CodeUri: go1.0/hello-world/
      Handler: hello-world
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /go10
            Method: GET
      #Environment:# More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
      #Variables:
      #  THUNDRA_APIKEY: f1b50fe3-ec46-4fb7-a560-fecaf1985266

  Node14Function:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: Node14-HelloWorld
      CodeUri: node14/hello-world/
      Handler: thundra_handler.wrapper
      Runtime: nodejs14.x
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /node14
            Method: get
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:${ThundraAWSAccountNo}:layer:thundra-lambda-node-layer:${ThundraNodeLayerVersion}
      Environment:
        Variables:
          THUNDRA_AGENT_LAMBDA_HANDLER: app.lambdaHandler

  Python39Function:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: Python39-HelloWorld
      CodeUri: python3.9/hello_world/
      Handler: thundra.handler.wrapper
      Runtime: python3.9
      Environment:
        Variables:
          thundra_agent_lambda_handler: app.lambda_handler
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /python39
            Method: get
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:${ThundraAWSAccountNo}:layer:thundra-lambda-python-layer:${ThundraPythonLayerVersion}

Outputs:
  EndpointOfAllLambdas:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
